version: '3'
services:
  golang:
    image: golang:1.19.3
    volumes: 
      - ./:/root/myproject
    entrypoint: tail -f /dev/null
    environment:
      - GOPATH=/root/myproject/packages
      - TZ=Asia/Tokyo
    ports:
    - 8080:8080
